import os
from pathlib import Path

#SERVICE
#url
USER_SERVICE_URL = os.getenv('USER_SERVICE_URL')
PARSER_SERVICE_URL = os.getenv('PARSER_SERVICE_URL')
LLMCLIENT_SERVICE_URL = os.getenv('LLMCLIENT_SERVICE_URL')
#STORAGE
STORAGE_DIR = Path(os.getenv('STORAGE_DIR'))
#user
STORAGE_USER_FILE_PATH = STORAGE_DIR / os.getenv("USER_PATENTS_PATH")
STORAGE_USER_DATA_DIR = STORAGE_DIR / os.getenv("USER_DATA_DIR")

#prompt
STORAGE_PROMPTS_DIR = STORAGE_DIR / os.getenv('STORAGE_PROMPTS_DIR')

#LOGS
LOG_DIR = os.getenv('LOG_DIR')
LOG_FILE_SYSTEM = os.getenv('LOG_FILE_SYSTEM')
LOG_FILE_USER = os.getenv('LOG_FILE_USER')
LOG_MAX_BYTES = 10 * 1024 * 1024  # 10 MB
LOG_BACKUP_COUNT = 5
LOG_ENCODING = 'utf-8'
# Format
LOG_SYSTEM_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
LOG_USER_FORMAT = '%(asctime)s - %(message)s'
# Logging levels
LOG_FILE_LEVEL = 'INFO'
LOG_CONSOLE_LEVEL = 'DEBUG'
LOG_ROOT_LEVEL = 'DEBUG'
LOG_WERKZEUG_LEVEL = 'INFO'

DEBUG = True
